version: '3.0'

services:
  db:
    image: mongo:4.4.29
    container_name: realtimedb
    ports:
      - "27017:27017"
    volumes:
      - realtime-volume:/data/db
  
  app:
    image: realtime
    container_name: realtime
    env_file: config/.env
    ports:
      - "3000:3000"
    
    depends_on:
      - db

volumes:
  realtime-volume:
